-- easyssf 0.1.0: the tables of the JDBC stores, with the default table prefix.
-- Timestamps are milliseconds since the epoch. On Oracle use NUMBER(19) instead of BIGINT.

CREATE TABLE EASYSSF_PROCESSED_SET (
    ISSUER VARCHAR(255) NOT NULL,
    JTI VARCHAR(255) NOT NULL,
    PROCESSED_AT BIGINT NOT NULL,
    CONSTRAINT EASYSSF_PROCESSED_SET_PK PRIMARY KEY (ISSUER, JTI)
);
CREATE INDEX EASYSSF_PROCESSED_SET_IX1 ON EASYSSF_PROCESSED_SET (PROCESSED_AT);

CREATE TABLE EASYSSF_REVOCATION (
    KIND VARCHAR(16) NOT NULL,
    ISSUER VARCHAR(255) NOT NULL,
    ID VARCHAR(255) NOT NULL,
    REVOKED_AT BIGINT NOT NULL,
    EXPIRES_AT BIGINT NOT NULL,
    CONSTRAINT EASYSSF_REVOCATION_PK PRIMARY KEY (KIND, ISSUER, ID)
);
CREATE INDEX EASYSSF_REVOCATION_IX1 ON EASYSSF_REVOCATION (EXPIRES_AT);
