-- easyssf 0.3.0: the state of a processed SET (IN_PROGRESS while its handlers run), and the acknowledgements a
-- polling receiver owes its transmitter.

ALTER TABLE EASYSSF_PROCESSED_SET ADD STATE VARCHAR(16) DEFAULT 'PROCESSED' NOT NULL;

CREATE TABLE EASYSSF_POLL_ACK (
    ISSUER VARCHAR(255) NOT NULL,
    JTI VARCHAR(255) NOT NULL,
    ERROR_CODE VARCHAR(64),
    ERROR_DESCRIPTION VARCHAR(1024),
    RECORDED_AT BIGINT NOT NULL,
    CONSTRAINT EASYSSF_POLL_ACK_PK PRIMARY KEY (ISSUER, JTI)
);
CREATE INDEX EASYSSF_POLL_ACK_IX1 ON EASYSSF_POLL_ACK (RECORDED_AT);
