-- Tables of the JDBC stores of the easyssf receiver.
-- Timestamps are milliseconds since the epoch. On Oracle use NUMBER(19) instead of BIGINT.

-- SETs that were processed, see JdbcSsfJtiDedupStore
CREATE TABLE EASYSSF_PROCESSED_SET (
    ISSUER VARCHAR(255) NOT NULL,
    JTI VARCHAR(255) NOT NULL,
    PROCESSED_AT BIGINT NOT NULL,
    CONSTRAINT EASYSSF_PROCESSED_SET_PK PRIMARY KEY (ISSUER, JTI)
);
CREATE INDEX EASYSSF_PROCESSED_SET_IX1 ON EASYSSF_PROCESSED_SET (PROCESSED_AT);

-- revoked sessions (KIND 'SESSION') and subjects (KIND 'SUBJECT'), see JdbcSsfTokenRevocationStore
CREATE TABLE EASYSSF_REVOCATION (
    KIND VARCHAR(16) NOT NULL,
    ID VARCHAR(255) NOT NULL,
    REVOKED_AT BIGINT NOT NULL,
    EXPIRES_AT BIGINT NOT NULL,
    CONSTRAINT EASYSSF_REVOCATION_PK PRIMARY KEY (KIND, ID)
);
CREATE INDEX EASYSSF_REVOCATION_IX1 ON EASYSSF_REVOCATION (EXPIRES_AT);
