<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.easyssf</groupId>
        <artifactId>easyssf-parent</artifactId>
        <version>0.1.0</version>
    </parent>
    <artifactId>easyssf-receiver-spring-boot-examples</artifactId>
    <name>easyssf-receiver-spring-boot-examples</name>
    <description>Example applications that receive security events from a Keycloak SSF transmitter</description>
    <packaging>pom</packaging>

    <modules>
        <module>example-resource-server</module>
        <module>example-oidc-client</module>
    </modules>

    <properties>
        <maven.deploy.skip>true</maven.deploy.skip>
    </properties>


</project>
